niveau_index:
    path:     /
    defaults: { _controller: "AdminBundle:SkNiveau:index" }
    methods:  [POST,GET]

niveau_new:
    path:     /new
    defaults: { _controller: "AdminBundle:SkNiveau:new" }
    methods:  [GET, POST]
    
niveau_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:SkNiveau:update" }
    methods:  [GET, POST]

niveau_add_class:
    path:     /{id}/classe
    defaults: { _controller: "AdminBundle:SkNiveau:addClassForNiveau" }
    methods:  [GET, POST]

niveau_list_class:
    path:     /{id}/class/list
    defaults: { _controller: "AdminBundle:SkNiveau:getAllNiveauClass" }
    methods:  [GET, POST]

#niveau_update:
#    path:     /{id}/update
#    defaults: { _controller: "U" }
#    methods:  [POST, PUT]

niveau_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:SkNiveau:delete" }
    methods:  [GET, DELETE]
